### ISSUE TITLE
Allow specifying default revision for the lab

### ISSUE THREAD

**Issue by siamaksade** [openshift-evangelists/openshift-workshops#5]
When defining labs, user can specify a revision for each module. It should be possible to define a default revision scoped to the entire lab which applies to all modules. Each module should still be able to override the default revision.

```
name: OpenShift 3 Roadshow
vars:
  DOCS_URL: "docs.openshift.com/container-platform"
  SUFFIX: "XX"
  USER_SUFFIX: "-XX"
revision: roadshow
modules:
  revisions:
    codechanges: eap7
```
