### ISSUE TITLE
Lab: Automating Deployment with CI/CD Pipeline

### ISSUE THREAD

**Issue by VeerMuchandi** [openshift-evangelists/openshift-workshops#55]
In the step "Live Deployment", when you deploy an application pointing to the image with "live" tag, but if you rename the app to "nationalparks-live", the trigger in the deployment configuration is set to "national parks-live:live"

See below:
  triggers:
    -
      type: ConfigChange
    -
      type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - nationalparks-live
        from:
          kind: ImageStreamTag
          namespace: explore-00
          name: 'nationalparks-live:live’

This is preventing the application from getting deployed. I had to manually change the from image name to national parks:live.

**Comment by thoraxe** [comment]
No one has experienced this problem. Can you describe the exact steps you are taking to get there? Your YAML is also badly formatted.

It looks like you may have failed to correctly select the right image to be used, or completed the steps in the wrong order.

**Comment by VeerMuchandi** [comment]
All I did was when deploying the nationalparks-live app, I selected the nationalparks image and changed the name of the app to nationalparks-live as instructed in the lab. This changed the trigger to use nationalparks-live:live instead of nationalparks:live. I had to edit the DC to fix the trigger to get the app to deploy.

**Comment by thoraxe** [comment]
FYI I just did this lab again:

```YAML
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - nationalparks-live
      from:
        kind: ImageStreamTag
        name: nationalparks:live
        namespace: explore-00
      lastTriggeredImage: 172.30.227.235:5000/explore-00/nationalparks@sha256:b2e1d95769b7eedac6461596bd584582b2c7c47944bc578939860bab9eebf6e5
    type: ImageChange
```
